### ISSUE TITLE
Exception within PDE when renaming feature containing a product

### ISSUE THREAD

**Issue by edscadding** [secondfiddle/pep-tools#6]
This exception occurred when renaming a feature that contained a product.

```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to org.eclipse.pde.core.IModel
                at uk.org.secondfiddle.eclipse.product.nature.model.WorkspaceProductModelManager.removeModel(WorkspaceProductModelManager.java:69)
                at org.eclipse.pde.internal.core.WorkspaceModelManager.visit(WorkspaceModelManager.java:150)
                at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:69)
                at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
                at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:49)
                at org.eclipse.pde.internal.core.WorkspaceModelManager.handleResourceDelta(WorkspaceModelManager.java:125)
                at org.eclipse.pde.internal.core.WorkspaceModelManager.resourceChanged(WorkspaceModelManager.java:113)
                at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
                at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
                at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
                at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
                at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:396)
                at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1531)
                at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:45)
                at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

**Comment by edscadding** [comment]
Cannot reproduce - looks like the problem was in a much earlier version of the plugin.
