### ISSUE TITLE
Exceptions within Eclipse extension registry, likely due to project template

### ISSUE THREAD

**Issue by edscadding** [secondfiddle/pep-tools#7]
As summary. These exceptions may have been caused by removing and then re-adding a project containing templates.

```
org.eclipse.core.runtime.InvalidRegistryObjectException: Invalid registry object
                at org.eclipse.core.internal.registry.TemporaryObjectManager.getObject(TemporaryObjectManager.java:98)
                at org.eclipse.core.internal.registry.ConfigurationElementHandle.getConfigurationElement(ConfigurationElementHandle.java:26)
                at org.eclipse.core.internal.registry.ConfigurationElementHandle.getParent(ConfigurationElementHandle.java:103)
                at org.eclipse.core.internal.registry.ConfigurationElementHandle.getDeclaringExtension(ConfigurationElementHandle.java:93)
                at org.eclipse.core.internal.registry.ConfigurationElementHandle.getNamespaceIdentifier(ConfigurationElementHandle.java:130)
                at org.eclipse.ui.internal.dialogs.WorkbenchWizardElement.getPluginId(WorkbenchWizardElement.java:238)
                at org.eclipse.ui.activities.WorkbenchActivityHelper.createUnifiedId(WorkbenchActivityHelper.java:180)
                at org.eclipse.ui.activities.WorkbenchActivityHelper.getIdentifier(WorkbenchActivityHelper.java:57)
                at org.eclipse.ui.activities.WorkbenchActivityHelper.allowUseOf(WorkbenchActivityHelper.java:104)
                at org.eclipse.ui.activities.WorkbenchActivityHelper.restrictUseOf(WorkbenchActivityHelper.java:122)
                at org.eclipse.ui.internal.dialogs.WizardCollectionElement.getWorkbenchWizardElementsExpression(WizardCollectionElement.java:286)
                at org.eclipse.ui.internal.dialogs.WizardCollectionElement.getWorkbenchWizardElements(WizardCollectionElement.java:268)
                at org.eclipse.ui.internal.wizards.AbstractExtensionWizardRegistry.registerWizards(AbstractExtensionWizardRegistry.java:142)
                at org.eclipse.ui.internal.wizards.AbstractExtensionWizardRegistry.registerWizards(AbstractExtensionWizardRegistry.java:153)
                at org.eclipse.ui.internal.wizards.AbstractExtensionWizardRegistry.addExtension(AbstractExtensionWizardRegistry.java:60)
                at org.eclipse.ui.internal.registry.UIExtensionTracker$2.run(UIExtensionTracker.java:64)
                at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:164)
                at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:158)
                at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
                at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
                at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145)
                at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3762)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
                at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
                at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
                at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
                at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
                at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
                at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
                at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
                at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
                at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
```

```
org.eclipse.core.runtime.InvalidRegistryObjectException: Invalid registry object
                at org.eclipse.core.internal.registry.TemporaryObjectManager.getObject(TemporaryObjectManager.java:98)
                at org.eclipse.core.internal.registry.ConfigurationElementHandle.getConfigurationElement(ConfigurationElementHandle.java:26)
                at org.eclipse.core.internal.registry.ConfigurationElementHandle.getParent(ConfigurationElementHandle.java:103)
                at org.eclipse.core.internal.registry.ConfigurationElementHandle.getDeclaringExtension(ConfigurationElementHandle.java:93)
                at org.eclipse.core.internal.registry.ConfigurationElementHandle.getNamespaceIdentifier(ConfigurationElementHandle.java:130)
                at org.eclipse.ui.internal.dialogs.WorkbenchWizardElement.getPluginId(WorkbenchWizardElement.java:238)
                at org.eclipse.ui.activities.WorkbenchActivityHelper.createUnifiedId(WorkbenchActivityHelper.java:180)
                at org.eclipse.ui.activities.WorkbenchActivityHelper.getIdentifier(WorkbenchActivityHelper.java:57)
                at org.eclipse.ui.activities.WorkbenchActivityHelper.allowUseOf(WorkbenchActivityHelper.java:104)
                at org.eclipse.ui.activities.WorkbenchActivityHelper.restrictUseOf(WorkbenchActivityHelper.java:122)
                at org.eclipse.ui.internal.dialogs.WizardCollectionElement.getWizardsExpression(WizardCollectionElement.java:253)
                at org.eclipse.ui.internal.dialogs.WizardCollectionElement.getWizards(WizardCollectionElement.java:238)
                at org.eclipse.ui.internal.dialogs.WizardCollectionElement.findWizard(WizardCollectionElement.java:167)
                at org.eclipse.ui.internal.dialogs.WizardCollectionElement.findWizard(WizardCollectionElement.java:180)
                at org.eclipse.ui.internal.wizards.AbstractWizardRegistry.findWizard(AbstractWizardRegistry.java:71)
                at org.eclipse.ui.actions.BaseNewWizardMenu.getAction(BaseNewWizardMenu.java:187)
                at org.eclipse.ui.actions.BaseNewWizardMenu.addShortcuts(BaseNewWizardMenu.java:150)
                at org.eclipse.ui.actions.NewWizardMenu.addItems(NewWizardMenu.java:171)
                at org.eclipse.ui.actions.BaseNewWizardMenu.getContributionItems(BaseNewWizardMenu.java:213)
                at org.eclipse.ui.actions.NewWizardMenu.getContributionItems(NewWizardMenu.java:228)
                at org.eclipse.ui.actions.CompoundContributionItem.getContributionItemsToFill(CompoundContributionItem.java:93)
                at org.eclipse.ui.actions.CompoundContributionItem.fill(CompoundContributionItem.java:60)
                at org.eclipse.jface.action.MenuManager.doItemFill(MenuManager.java:746)
                at org.eclipse.jface.action.MenuManager.update(MenuManager.java:827)
                at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:477)
                at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:470)
                at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:500)
                at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:255)
                at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
                at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
                at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
                at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1062)
                at org.eclipse.swt.widgets.Control.WM_INITMENUPOPUP(Control.java:4964)
                at org.eclipse.swt.widgets.Control.windowProc(Control.java:4640)
                at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
                at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1627)
                at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2075)
                at org.eclipse.swt.widgets.Display.windowProc(Display.java:4977)
                at org.eclipse.swt.internal.win32.OS.TrackPopupMenu(Native Method)
                at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:257)
                at org.eclipse.swt.widgets.Display.runPopups(Display.java:4211)
                at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3753)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
                at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
                at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
                at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
                at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
                at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
                at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
                at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
                at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
                at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
```

**Comment by edscadding** [comment]
Fixed by dd688c1e1a8f7c965a9bd2761803ace2ca29539d
